import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navigation from "./components/common/Navigation";
import { navgationDataGet } from "./utils/api/apiList";
import { ToastContainer } from "react-toastify";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navbar = await navgationDataGet();
  // console.log(navbar, "checking data");
  const navbarDetails = navbar.data;
  //  console.log(navbarDetails?.header , 'btnbtnbtnbtn')
  return (
    <html lang="en" className={`${poppins.variable} h-full antialiased`}>
      <body className="">
        <Navigation navbarDetails={navbarDetails} />
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
